{
 "title": "DHCP(성남)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "found IP 이벤트 카운트",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"coredhcp\", app=\"coredhcp\"} |= \"found IP address\" [1m])"
    }
   ]
  },
  {
   "title": "최근 할당(lease) 이벤트 카운트",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"coredhcp\", app=\"coredhcp\"} |= \"leasing new IPv4 address\" [1m])"
    }
   ]
  },
  {
   "title": "CoreDHCP Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"coredhcp\", app=\"coredhcp\"}"
    }
   ]
  },
  {
   "title": "최근 할당된 IP / MAC 목록",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"coredhcp\", app=\"coredhcp\"} |= \"found IP address\""
    }
   ]
  }
 ]
}